services:
- mongodb
notifications:
  hipchat:
    rooms:
      secure: uz1MFTxcZrs0eDiMhPhCbERK9nmmVCoEtuxiAM3E2gPWxPmDBNgSd7yE8KGYfPhHmKq+wan3ygwu+1GsY0+rrn/I5Ubpwhn14U5XkU+tWb2PUrdiCICRRfrmw3D0SCPKJSKWHmKHpKIodyUKm/C1rYK6UrDT5RUBAr6yDaUAql4=
