services:
- mongodb
notifications:
  hipchat:
    rooms:
      secure: O5w85rBXPn2Yk+9N6WBQirfJNo17eklHEt0iXxFpgKQ0luEXoKEMVUnPXpl+6vCL041yP8Ssz4p1Thm671eRjjrOZmr3OIThWaXtUzh5sQoDt5KVl5UBOqgJg6Mck1SvNHFz67BJfIN8DveKZHYilgY1dqXBLHB4h3guaiZaa4k=
